/*
 * This Java source file was generated by the Gradle 'init' task.
 */

/*
 * @author Camille Koestli <camille.koestli@heig-vd.ch>
 * @author Vitória Oliveira <maria.cosmodeoliveira@heig-vd.ch>
 */
package dai;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws InterruptedException, IOException {
        if(args.length == 0){
            System.out.println("Please provide an instrument name as a command-line argument.");
            System.exit(1);
        }

        String instrument = args[0];
        System.out.println("Instrument provided: " + instrument);   //TODO test

        Musician musician = new Musician(instrument);

        System.out.println("Musician created: " + musician.getInstrument() + " " + musician.getSound());

        MusicianBroadcastSender sender = new MusicianBroadcastSender(musician);

        System.out.println("Starting sender...");

        while(true){
            sender.run("");
            Thread.sleep(1000);
        }
    }
}